# 공통 이미지 및 scripte 내용
default:
  image: 'busybox:latest'

# 공통 anchor 설정 
.common-feature: &common-feature
  allow_failure: false
  tags :
   - sdh-test-runner

.some-script-before: &some-script-before
  - echo "Execute this script first"
  - sleep 5

.some-script: &some-script
  - echo "Execute this script second"
  - echo "Execute this script too"

.some-script-after: &some-script-after
  - echo "Execute this script last"
  - sleep 5

.tags-info: &tags-info
  tags : 
    - sdh-test-runner
    

###############
# 공통 변수 값 설정
###############

variables:
  TF_DIR : "vpc"
  TAGS   : "sdh-test-runner"

###############
# CI Pipeline
###############

stages:
  - validation
  - plan
  - apply
  - destroy

validation:
  stage: validation
  <<: *common-feature

  # before_script:
  #   - *some-script-before

  script:
    - echo "VPC terraform validation"
    - terraform validate
  
  # after_script:
  #   - *some-script-after
  
  # tags:
  #   - ${TAGS}

plan:
  stage: plan
  <<: *common-feature
  
  script :
   - |
    echo "VPC terraform plan"
    terraform plan -out=plan.txt -refresh=false
  artifacts:
    paths:
      - ./plan.txt
  
  # tags:
  # - ${TAGS}

apply:
  stage: apply
  <<: *common-feature

  script:
   - |
     echo "VPC terraform apply"
     terraform apply plan.txt
  when: manual
  # tags:
  # - ${TAGS}



.destroy:
  stage: destroy
  <<: *common-feature
  
  script:
    - |
    echo "VPC terraform destroy"
    terraform destroy plan.txt

  # tags:
  # - ${TAGS}