stages :
  - triggers

vpc :
  stage : triggers
  # 'trigger' is the keyword to create a child pipeline
  trigger :
    include: main/vpc/.gitlab-ci.yml
    strategy: depend

  allow_failure: false

#################################
### route-table
#################################

bastion-route-table :
  stage : triggers
  # needs : 
    # - vpc 
  trigger :
    include: main/route-table/bastion-route-table/.gitlab-ci.yml
    strategy: depend # 사용할 경우 CI/CD 설정이 Running으로 표시, 주석처리 할 경우 시작과 동시에 완료 상관 없이 Finish로 변경

mgmt-route-table :
  stage : triggers
  # needs : 
    # - vpc 
  trigger :
    include: main/route-table/mgmt-route-table/.gitlab-ci.yml
    strategy: depend # 사용할 경우 CI/CD 설정이 Running으로 표시, 주석처리 할 경우 시작과 동시에 완료 상관 없이 Finish로 변경

eks-route-table :
  stage : triggers
  # needs : 
    # - vpc 
  trigger :
    include: main/route-table/eks-route-table/.gitlab-ci.yml
    strategy: depend # 사용할 경우 CI/CD 설정이 Running으로 표시, 주석처리 할 경우 시작과 동시에 완료 상관 없이 Finish로 변경

db-route-table :
  stage : triggers
  # needs : 
    # - vpc 
  trigger :
    include: main/route-table/db-route-table/.gitlab-ci.yml
    strategy: depend # 사용할 경우 CI/CD 설정이 Running으로 표시, 주석처리 할 경우 시작과 동시에 완료 상관 없이 Finish로 변경

#################################
### security-group
#################################

bastion-security-group :
  stage : triggers
  # needs : 
    # - vpc # vpc가 끝나야 작업을 진행 strategy와 같이 사용
  trigger :
    include: main/security-group/bastion-security-group/.gitlab-ci.yml
    strategy: depend

mgmt-security-group :
  stage : triggers
  needs : 
    - bastion-security-group 
  trigger :
    include: main/security-group/mgmt-security-group/.gitlab-ci.yml
    strategy: depend

eks-security-group :
  stage : triggers
  needs : 
    - bastion-security-group 
  trigger :
    include: main/security-group/eks-security-group/.gitlab-ci.yml
    strategy: depend

#################################
### security-group-rule
#################################

bastion-security-group-rule :
  stage : triggers
  needs : 
    - bastion-security-group 
  trigger :
    include: main/security-group-rule/bastion-security-group-rule/.gitlab-ci.yml
    strategy: depend

mgmt-security-group-rule :
  stage : triggers
  needs : 
    - mgmt-security-group 
  trigger :
    include: main/security-group-rule/mgmt-security-group-rule/.gitlab-ci.yml
    strategy: depend

eks-security-group-rule :
  stage : triggers
  needs : 
    - eks-security-group
  trigger :
    include: main/security-group-rule/eks-security-group-rule/.gitlab-ci.yml
    strategy: depend
